trainer_config:
  max_epochs: 60
  batch_size: 1024
  data_loader_workers: 16 
  grad_norm_clip: 0.8
  snapshot_path: transformer-1.pt
  save_every: 15
  use_amp: False
  use_wandb: True
  run_name: transformer-1.pt
  use_lr_scheduler: True
lr_scheduler_config:
  type: plateau
  gamma: 0.5
  patience: 4
  mode: min
  threshold: 0.001
optimizer_config:
  optimizer: adam
  weight_decay: 0.00001
  learning_rate: 0.0005
data_config:
  train_percentage: 0.98
model_config:
  upscale_schedule: [8, 16, 32, 64, 77]
  nhead: 8
  num_transformer_layers: 3
compile: False

