trainer_config:
  max_epochs: 100
  batch_size: 1024
  data_loader_workers: 16 
  grad_norm_clip: 0.8
  snapshot_path: full-run-3.pt
  save_every: 3
  use_amp: False
  use_wandb: True
  run_name: full-run-3
  use_lr_scheduler: True
lr_scheduler_config:
  type: plateau
  gamma: 0.3
  patience: 4
  mode: min
  threshold: 0.02
optimizer_config:
  optimizer: adam
  weight_decay: 0.00001
  learning_rate: 0.001
data_config:
  train_percentage: 0.98
model_config:
  upscale_schedule: [8, 16, 32, 64, 77]
compile: False

